### ISSUE TITLE
folderview: icon on desktop: if an icon is clicked once and doubleclick enabled, the right click on a selected icon does not bring up context menu of icon, but desktop context menu

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.5#19]

**Comment by eikehein** [comment]
I can't reproduce it: http://eikehein.com/fv_ctxtmenu.mkv

Could I get a video to think more? :)

**Comment by eikehein** [comment]
I poked things a bit more, and I'm seeing an issue where if you:

a) Open the desktop context menu
b) Dismiss it by right-clicking on an icon (doesn't open new menu as expected, just closes the old one)
c) Right-click again without mouse movement

... you get the wrong menu. The same happens in reverse (from icon to desktop).

There's some sort of fundamental low-level Qt bug here in the interaction between Qt Quick and QWidget (the context menu is a QMenu). In the absence of mouse movement after the mouse grabber (the menu) is gone, some sort of internal state about who is receiving mouse events right now is not updated and the mouse press event is delivered to the wrong item. Only a mouse move event updates things.

I have to dig deeper into Qt code to find the cause for this. Most likely the fix will have to be done in Qt and involve doing a check that happens on move events also in the button event handler.

**Comment by eikehein** [comment]
Further investigation results: It's a really low-level bug in Qt causing an XCB enter_notify event (what the window under the pointer gets after a mouse grabbing menu was dismissed by click) not to propagate the state down to a QQuickWindow's content item as a hoverEnterEvent. Because Folder View doesn't know it's being hovered it can't set the acceptedButtons property to fit what's being hovered before the subsequent click event, disabling the right mouse button handling and causing the click to go through to the containment.

**Comment by eikehein** [comment]
This is fundamentally because Qt Quick was written for touch first and not mouse support - QWidget has an enterEvent handler, but QWindow (and thus QQuickWindow) doesn't. There's no facility to handle an enter without a move, so there's no attempt made to convert the XCB enter_notify event into a hoverEnterEvent. A hoverEnterEvent is contingent on a mouse move. This isn't an issue for touch interaction because touch point appearance is handled in a different way.

So as far as options I can see:
- Work upstream to fix this fundamental problem
- Quicker workaround hack in Qt to trigger a hEE by synthesizing a mouse move on enter_notify (Qt contains some similar hacks in other places, so maybe could even be accepted)
- Try to find a workaround just in FV (or our MouseEventListener component) to at least handle the click event (i.e. some way to set the right accepted buttons without requiring the hover first to figure out what's being hovered ... fun) and give up on realtime hover being correct after mouse grabber dismissal

I'll probably do the last one first and then see about the others ...

**Comment by eikehein** [comment]
Proposed Qt patch: https://codereview.qt-project.org/146786
