### ISSUE TITLE
[discover]: discover/packagekit failed with unkown error

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.5#23]
![screenshot_20160221_175704](https://cloud.githubusercontent.com/assets/840070/13204035/7506fcc0-d8c5-11e5-991d-cddcae8a0207.png)

It was starting to download all 235 packages also showing correct package sizes, then after ~1hour, it suddenly failed with above message, setting all sizes in background to 0B.
Any idea what might have caused this?

**Comment by star-buck** [comment]
![screenshot_20160221_165255](https://cloud.githubusercontent.com/assets/840070/13204059/151e867e-d8c6-11e5-96e5-62df45690ce6.png)
this is how it started (I noticed that Libreoffice update was 81MB for each App, maybe it was 81MB for the whole LO update and not 5x81MB?)

**Comment by aleixpol** [comment]
No, the size issue is just in the front-end and was being worked on.

We can maybe find more information on the issue in the pacman logs (I'm assuming this is on an ArchLinux-based distribution, otherwise tell me and we'll find where to look).
`cat /var/log/pacman.log` should offer such information.

Other things to see is which state does pacman/discover start after the issue.
